-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Фев 10 2023 г., 14:26
-- Версия сервера: 8.0.30
-- Версия PHP: 8.1.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `f0727777_wood-decor`
--

-- --------------------------------------------------------

--
-- Структура таблицы `category`
--

CREATE TABLE `category` (
  `id` int NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rus_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `category`
--

INSERT INTO `category` (`id`, `name`, `rus_name`, `description`) VALUES
(1, 'wood products', 'изделия из дерева', 'Продукция из древесины всегда пользовалась широким спросом и остается крайне популярной. Изготовление изделий из дерева­ является основным направлением нашей работы');

-- --------------------------------------------------------

--
-- Структура таблицы `shop_products`
--

CREATE TABLE `shop_products` (
  `id` int NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `price` float NOT NULL,
  `quantity` int NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_active` int NOT NULL DEFAULT '1',
  `category_id` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `shop_products`
--

INSERT INTO `shop_products` (`id`, `title`, `price`, `quantity`, `description`, `image`, `is_active`, `category_id`) VALUES
(1, 'Aliquid facilis', 1500, 5, 'Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam.', '/template/images/catalog/2022-12-30-17.41.45.jpeg', 1, 1),
(2, 'A consequuntur ipsum', 400, 3, 'Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis. Asperiores expedita voluptatum veritatis voluptatibus perspiciatis nostrum! Culpa quibusdam aliquid, voluptatibus, officiis tempora veritatis doloribus quisquam explicabo velit quam\r\nest reprehenderit dignissimos unde corporis blanditiis facere hic, perferendis quo sapiente quia laborum qui beatae! Ratione, eligendi.', '/template/images/catalog/2022-12-30-17.41.46.jpeg', 1, 1),
(3, 'Sint cumque commodi', 478, 7, 'Aliquid facilis ducimus fuga voluptate, illo quis quos\r\nearum fugiat modi delectus quisquam cumque quo obcaecati! Laboriosam voluptate beatae repellendus est quibusdam reprehenderit ipsam consectetur ut. Accusamus, odit perferendis omnis facilis, provident\r\nexercitationem accusantium soluta earum eligendi itaque, sapiente deleniti! Tempore laborum nesciunt possimus blanditiis adipisci voluptates doloribus impedit officia animi aliquid explicabo\r\nrepudiandae sit assumenda officiis omnis, natus esse praesentium incidunt ratione quos ullam nulla qui? Vero quisquam, placeat modi, sed quia id illum esse maxime a perspiciatis iure vel voluptatibus\r\nfacilis quod! A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi.', '/template/images/catalog/2022-12-30-17.41.47.jpeg', 1, 1),
(4, 'Recusandae possimus', 700, 5, 'Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo.', '/template/images/catalog/2022-12-30-17.41.48.jpeg', 1, 1),
(5, 'Ea ullam nihil', 900, 4, 'Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam?', '/template/images/catalog/2022-12-30-17.41.49.jpeg', 1, 1),
(6, 'Lorem ipsum ', 1200, 8, 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, delectus enim ea vitae fugit temporibus dolores eius nisi nihil reiciendis porro, est unde veritatis dicta quia assumenda sit\r\nreprehenderit neque modi, labore voluptatibus. Sint cumque commodi nisi corporis? Repellat enim nemo rerum magnam voluptatem earum corporis! Aliquid facilis ducimus fuga voluptate, illo quis quos\r\nearum fugiat modi delectus quisquam cumque quo obcaecati! Laboriosam voluptate beatae repellendus est quibusdam reprehenderit ipsam consectetur ut. Accusamus, odit perferendis omnis facilis, provident\r\nexercitationem accusantium soluta earum eligendi itaque, sapiente deleniti! Tempore laborum nesciunt possimus blanditiis adipisci voluptates doloribus impedit officia animi aliquid explicabo\r\nrepudiandae sit assumenda officiis omnis, natus esse praesentium incidunt ratione quos ullam nulla qui? Vero quisquam, placeat modi, sed quia id illum esse maxime a perspiciatis iure vel voluptatibus\r\nfacilis quod!', '/template/images/catalog/2022-12-30-17.41.50.jpeg', 1, 1),
(7, 'Nobis non expedita ', 599, 6, 'A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus.', '/template/images/catalog/2022-12-30-17.41.51.jpeg', 1, 1),
(8, 'Repudiandae soluta', 1400, 3, 'Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis. Asperiores expedita voluptatum veritatis voluptatibus perspiciatis nostrum! Culpa quibusdam aliquid, voluptatibus, officiis tempora veritatis doloribus quisquam explicabo velit quam\r\nest reprehenderit dignissimos unde corporis blanditiis facere hic, perferendis quo sapiente quia laborum qui beatae! Ratione, eligendi.\r\n', '/template/images/catalog/2022-12-30-17.41.52.jpeg', 1, 1),
(9, 'Modi quasi obcaecati', 699, 2, 'Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo.', '/template/images/catalog/2022-12-30-17.41.53.jpeg', 1, 1),
(10, 'Recusandae possimus ex', 2800, 6, 'Aliquid facilis ducimus fuga voluptate, illo quis quos\r\nearum fugiat modi delectus quisquam cumque quo obcaecati! Laboriosam voluptate beatae repellendus est quibusdam reprehenderit ipsam consectetur ut. Accusamus, odit perferendis omnis facilis, provident\r\nexercitationem accusantium soluta earum eligendi itaque, sapiente deleniti! Tempore laborum nesciunt possimus blanditiis adipisci voluptates doloribus impedit officia animi aliquid explicabo\r\nrepudiandae sit assumenda officiis omnis, natus esse praesentium incidunt ratione quos ullam nulla qui? Vero quisquam, placeat modi, sed quia id illum esse maxime a perspiciatis iure vel voluptatibus\r\nfacilis quod! A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus.', '/template/images/catalog/2022-12-30-17.41.54(2).jpeg', 1, 1),
(11, 'Voluptatem dolorum et', 1100, 6, ' Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.41.54.jpeg', 1, 1),
(12, 'Culpa quibusdam aliquid', 1700, 5, 'Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis. Asperiores expedita voluptatum veritatis voluptatibus perspiciatis nostrum! Culpa quibusdam aliquid, voluptatibus, officiis tempora veritatis doloribus quisquam explicabo velit quam\r\nest reprehenderit dignissimos unde corporis blanditiis facere hic, perferendis quo sapiente quia laborum qui beatae! Ratione, eligendi.', '/template/images/catalog/2022-12-30-17.41.54-(1).jpeg', 1, 1),
(13, 'Recusandae possimus', 300, 8, 'Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.41.55(1).jpeg', 1, 1),
(14, 'Nobis non expedita', 3000, 2, 'A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores.', '/template/images/catalog/2022-12-30-17.41.55(2).jpeg', 1, 1),
(15, 'Tenetur qui quasi', 2400, 3, 'Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.41.55.jpeg', 1, 1),
(16, 'Ea ullam nihil', 1300, 1, 'Accusamus, odit perferendis omnis facilis, provident\r\nexercitationem accusantium soluta earum eligendi itaque, sapiente deleniti! Tempore laborum nesciunt possimus blanditiis adipisci voluptates doloribus impedit officia animi aliquid explicabo\r\nrepudiandae sit assumenda officiis omnis, natus esse praesentium incidunt ratione quos ullam nulla qui? Vero quisquam, placeat modi, sed quia id illum esse maxime a perspiciatis iure vel voluptatibus\r\nfacilis quod! A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi.', '/template/images/catalog/2022-12-30-17.41.56(1).jpeg', 1, 1),
(17, 'Cumque sit voluptas', 4000, 3, 'A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores.', '/template/images/catalog/2022-12-30-17.41.56(2).jpeg', 1, 1),
(18, 'Recusandae possimus ex', 2900, 2, 'Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia?', '/template/images/catalog/2022-12-30-17.41.56.jpeg', 1, 1),
(19, 'A consequuntur ipsum', 1600, 3, 'Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam.', '/template/images/catalog/2022-12-30-17.41.57(1).jpeg', 1, 1),
(20, 'Quod autem', 2356, 1, 'Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.41.57.jpeg', 1, 1),
(21, 'Voluptatem dolorum', 2455, 4, 'Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia?', '/template/images/catalog/2022-12-30-17.41.58(1).jpeg', 1, 1),
(22, 'Aliquid facilis', 3455, 2, 'Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.41.58.jpeg', 1, 1),
(23, 'Impedit voluptas', 7853, 5, 'Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis.', '/template/images/catalog/2022-12-30-17.41.59(1).jpeg', 1, 1),
(24, 'Impedit voluptas', 1569, 3, 'Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.41.59.jpeg', 1, 1),
(25, 'Libero eveniet', 3321, 7, 'Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.42.00.jpeg', 1, 1),
(26, 'Ex dolore eveniet', 6432, 4, ' Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.42.39.jpeg', 1, 1),
(27, 'Excepturi dicta magnam', 5699, 2, 'A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum?', '/template/images/catalog/2022-12-30-17.42.42(1).jpeg', 1, 1),
(28, 'Eligendi itaque', 2444, 6, 'Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste.', '/template/images/catalog/2022-12-30-17.42.42.jpeg', 1, 1),
(29, 'Voluptatum veritatis', 4335, 8, 'Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis. Asperiores expedita voluptatum veritatis voluptatibus perspiciatis nostrum! Culpa quibusdam aliquid, voluptatibus, officiis tempora veritatis doloribus quisquam explicabo velit quam\r\nest reprehenderit dignissimos unde corporis blanditiis facere hic, perferendis quo sapiente quia laborum qui beatae! Ratione, eligendi.\r\n', '/template/images/catalog/2022-12-30-17.42.44.jpeg', 1, 1),
(30, 'Excepturi dicta magnam', 1666, 8, 'Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores.', '/template/images/catalog/2022-12-30-17.41.46.jpeg', 1, 1),
(31, 'Itaque veritatis accusantium', 7111, 9, 'A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam?', '/template/images/catalog/2022-12-30-17.42.47.jpeg', 1, 1),
(32, 'Labore voluptatibus', 4888, 3, 'Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam.', '/template/images/catalog/2022-12-30-17.42.48.jpeg', 1, 1),
(33, 'Neque minus minima', 2889, 1, 'A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores.', '/template/images/catalog/2022-12-30-17.41.46.jpeg', 1, 1),
(36, 'Asperiores numquam', 1667, 7, 'Aliquid facilis ducimus fuga voluptate, illo quis quos\r\nearum fugiat modi delectus quisquam cumque quo obcaecati! Laboriosam voluptate beatae repellendus est quibusdam reprehenderit ipsam consectetur ut. Accusamus, odit perferendis omnis facilis, provident\r\nexercitationem accusantium soluta earum eligendi itaque, sapiente deleniti! Tempore laborum nesciunt possimus blanditiis adipisci voluptates doloribus impedit officia animi aliquid explicabo\r\nrepudiandae sit assumenda officiis omnis, natus esse praesentium incidunt ratione quos ullam nulla qui? Vero quisquam, placeat modi, sed quia id illum esse maxime a perspiciatis iure vel voluptatibus\r\nfacilis quod! A consequuntur ipsum neque minus minima quibusdam error unde, libero eveniet laudantium repellat animi odit maiores natus reprehenderit in? Nobis non expedita laboriosam error debitis!\r\nHarum provident, aperiam a fuga rem delectus, ipsum sunt rerum sequi modi possimus dolore architecto voluptas beatae aspernatur, eius minima libero perspiciatis nulla fugiat in? Quod autem, architecto\r\nsoluta voluptate aliquid numquam! Impedit voluptas, cum, eaque alias earum illum esse magnam aliquam exercitationem ab molestias soluta perspiciatis velit excepturi porro culpa commodi. Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam.', '/template/images/catalog/2022-12-30-17.42.49.jpeg', 1, 1),
(37, 'Tempore totam minus sed', 4123, 3, 'Ea ullam nihil\r\nodit dicta consectetur tempore totam minus sed, possimus explicabo. Cumque sit voluptas ad expedita dolores minima reprehenderit reiciendis numquam vitae debitis, harum voluptates similique delectus\r\ntempore quod, atque quis, necessitatibus ex dolore eveniet nemo aut exercitationem molestiae aliquid. Odio totam ullam, nesciunt optio porro temporibus odit placeat accusantium magni eaque nam. Harum\r\ndoloribus repudiandae rerum exercitationem aspernatur excepturi assumenda hic, consequatur eum dolorem dicta tenetur qui molestiae aliquam reprehenderit asperiores. Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam?', '/template/images/catalog/2022-12-30- 17.41.49-(2).jpeg', 1, 1),
(38, 'Ipsum neque minus', 388, 7, 'Recusandae possimus ex dicta qui\r\nporro, esse sed asperiores numquam ducimus. Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis. Asperiores expedita voluptatum veritatis voluptatibus perspiciatis nostrum! Culpa quibusdam aliquid, voluptatibus, officiis tempora veritatis doloribus quisquam explicabo velit quam\r\nest reprehenderit dignissimos unde corporis blanditiis facere hic, perferendis quo sapiente quia laborum qui beatae! Ratione, eligendi.\r\n', '/template/images/catalog/2022-12-3017.41.50(1).jpeg', 1, 1),
(39, 'Nulla fugiat in', 3789, 3, 'Earum assumenda aspernatur repellat pariatur deserunt quibusdam, sapiente, quisquam vero aliquam tempore laborum? Tenetur qui quasi aliquam. Repudiandae\r\nsoluta perspiciatis dolores in enim laborum aperiam ducimus unde, deserunt asperiores quis minima quos deleniti maiores nostrum, sequi fugiat accusamus tempore odit excepturi dicta magnam? Minima\r\narchitecto veniam dolorem molestiae? Modi quasi obcaecati reprehenderit officiis harum eveniet deleniti repellat, maiores non doloribus repudiandae eius itaque veritatis accusantium aliquam ex\r\ninventore libero! Similique temporibus accusantium, fuga quae tenetur nulla repudiandae dolores commodi excepturi. Voluptates est laudantium modi iure quo accusantium ullam rerum exercitationem\r\npossimus, corporis similique doloremque iste. Perferendis, ullam voluptates? Dolore porro voluptatibus quam maxime iure cum, odio dolor officiis explicabo esse animi asperiores minus dolorum deserunt\r\nbeatae dolores nihil mollitia? Voluptatem dolorum et quasi nobis, consectetur facilis autem vel in, nulla possimus ullam optio cumque rem cupiditate quis eaque deleniti porro accusamus quo. Excepturi\r\nharum, provident nam tempora natus labore architecto necessitatibus dicta ullam cumque nesciunt ut veritatis eveniet corrupti a ipsam atque maiores. Accusamus nostrum praesentium eius quod odio et\r\nmagni quo nobis.', '/template/images/catalog/2022-12-3017.41.51(1).jpeg', 1, 1);

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Индексы таблицы `shop_products`
--
ALTER TABLE `shop_products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `category`
--
ALTER TABLE `category`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT для таблицы `shop_products`
--
ALTER TABLE `shop_products`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;

--
-- Ограничения внешнего ключа сохраненных таблиц
--

--
-- Ограничения внешнего ключа таблицы `shop_products`
--
ALTER TABLE `shop_products`
  ADD CONSTRAINT `shop_products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
